# WILD APRICOT
wild-apricot.http.client-timeout = 25s
wild-apricot.http.max-pages = 20
wild-apricot.http.retries = 5
wild-apricot.http.retry-delay = 10s
wild-apricot.facility-code = 61
wild-apricot.fields.card-number = Jericho Card Number
wild-apricot.display-order.groups = Exec,Sailing - Beginner,Sailing - Intermediate I,Sailing - Intermediate II,Sailing - Advanced I,Sailing - Advanced II,Sailing - Advanced III,Sailing - Cat I,Sailing - Cat II,Sailing - Cat III,SUP, Windsurfing I,Windsurfing II,Windsurfing III - High Wind,Kayak I - Basic,Kayak II - Intermediate
wild-apricot.display-order.doors = Club Room Main,Club Room Slider,Fixit Room Main,Fixit Room Slider,Hobie Room,Windsurf L1 Locker,Windsurf L2 Locker,Kayak Locker,Exec Locker

# DEVICES

UT0311-L0x.423195692.address = 192.168.1.25:60000
UT0311-L0x.423195692.door.1 = Club Room Main
UT0311-L0x.423195692.door.2 = Hobie Room
UT0311-L0x.423195692.door.3 = Fixit Room Main
UT0311-L0x.423195692.door.4 = Fixit Room Slider

UT0311-L0x.423195744.address = 192.168.1.26:60000
UT0311-L0x.423195744.door.1 = UnusedD21
UT0311-L0x.423195744.door.2 = UnusedD22
UT0311-L0x.423195744.door.3 = Exec Locker
UT0311-L0x.423195744.door.4 = UnusedD24

UT0311-L0x.423195750.address = 192.168.1.27:60000
UT0311-L0x.423195750.door.1 = Kayak Locker
UT0311-L0x.423195750.door.2 = Windsurf L1 Locker
UT0311-L0x.423195750.door.3 = Windsurf L2 Locker
UT0311-L0x.423195750.door.4 = Club Room Slider
